### ISSUE TITLE
A couple of problems I had

### ISSUE THREAD

**Issue by EnterFor** [FifouBE/EconomyInc#10]
![image](https://user-images.githubusercontent.com/10114685/77558462-eb2f2600-6ef5-11ea-9db5-d177bd03a598.png)
I did not find the relevant string, I cannot translate it.

![image](https://user-images.githubusercontent.com/10114685/77558587-10bc2f80-6ef6-11ea-91fe-f18f30faca2b.png)
Is my texture wrong?
I don't remember it that way.
If you need to provide debug.log, please contact me.
I love this Mod! ~

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/77558935-86280000-6ef6-11ea-8f5f-4f24a4fff706.png)
This Can 't be translated? (I see localization doesn't seem to work)

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/77559541-49103d80-6ef7-11ea-9101-bde425d7b1f3.png)
![image](https://user-images.githubusercontent.com/10114685/77559681-69d89300-6ef7-11ea-8c5a-04444306e983.png)

This item shows a blank，unknown aetiology

**Comment by Florent98** [comment]
Hello, I will check for the block seller. Might have a problem with transparency texture not enabled in code. As for the block bills, it's a beta version, and Tile Entity Renderer (TER are actually WIP and are not working properly, so it will come). I will add the translation for the thing you asked! Thanks I leave this thread open so I can comment If I need more info :)

**Comment by EnterFor** [comment]
What's the progress?
I don't want to make you angry because I want to play it on the server too much
Apologize in advance:):)

**Comment by Florent98** [comment]
There is no progress for now. I had a huge data loss on my computer. I'm trying to get everything back. But some code needs debug because the code for the credit card when you die and respawn is there but it seams it's not working.

**Comment by Florent98** [comment]
I fixed the block seller appearance, the translations. Block bills is still WIP.
