### ISSUE TITLE
[1.15.2]It's me again, some advice

### ISSUE THREAD

**Issue by EnterFor** [FifouBE/EconomyInc#12]
1、Request to add string
![image](https://user-images.githubusercontent.com/10114685/77827895-3abe5d80-7153-11ea-8f27-3d23e99902db.png)

2、What should players do if they want to sell items over $500?

**Comment by Florent98** [comment]
I'll add the string. 

As I say for someone on curse. I will rework the seller. But i'm trying to update everything that needs to be updated first, before adding new stuff.

Thanks for the report

**Comment by Florent98** [comment]
I changed the string, it's not a new line in the lang file, it's the lines : 

"title.unlimitedStack":"unlimited",
"title.limitedStack":"limited",

since they already existed but were not used anymore, I use them now for that.
