### ISSUE TITLE
Help with balancing the gold and possible bug?

### ISSUE THREAD

**Issue by Kevo512** [FifouBE/EconomyInc#15]
Hey so i wanted to ask how do you configure the rates of Gold=Money when using the Gold Changer, because you said, in the curse page, that the admin could balance this, or change it atleast, and i can't find the option ( i tried with commands and with the mod options forge alternative )

and the other thing is that when i "cook" a gold ingot it gives me a golden nugget with a certain weight and then, (a couple seconds later) it changes the weight like from 0.35 to 0.62.

sorry if i wrote something with no sense or wrong, english is not my native language xd

![image](https://user-images.githubusercontent.com/62885490/77910574-bb6d7e80-7265-11ea-85df-94ad7a0ef8d7.png)

(and a couple seconds later)

![image](https://user-images.githubusercontent.com/62885490/77910607-c88a6d80-7265-11ea-8951-fbebbf1d592c.png)

**Comment by Florent98** [comment]
The mod config for server is on the world folder > serverconfig folder > economyinc-server.toml.

For the gold nugget issues, it might be a problem of sync client to server. But gold recipe is going to change, so for the moment please work with it before the new update that should resolve those problems.

**Comment by Kevo512** [comment]
Hi, thanks for answering so fast

Just for you to know, the golden nugget bug happened to me in singleplayer AND in multiplayer

Just wanted to clarify this and thank you

**Comment by Florent98** [comment]
Hi. Ok, but minecraft singleplayer has an internal server, so it's probably due to the fact that is not sync between the two entities. Thanks for the report! :)
