### ISSUE TITLE
Don't loot

### ISSUE THREAD

**Issue by epeeforteyt** [FifouBE/EconomyInc#18]
Hello, I have a question about your mod,

I can't relaunch the "Gold changer" with the mod key, is this normal or not?

In addition, there is no config file on the server side, any idea?

Version forge: forge-1.15.2-31.1.41.jar
Mod: EconomyInc 1.6.7 - MC1.15

**Comment by Florent98** [comment]
Hey! 

I don't understand your question about the gold changer ? What are you trying to do ?

Server config were moved from the config folder, they are now :
- Dedicated server : world/serverconfig
- Internal server (singleplayer) : saves/TheWorld/serverconfig

**Comment by epeeforteyt** [comment]
With the wrench, it is impossible for me to be able to resume the "Gold Changer" block even with silk touch: /

**Comment by Florent98** [comment]
Oh! Yeah I just saw that in the build. Will be fixed soon. I plan on releasing a patch certainly tomorrow, if not maybe this week-end. I just need to fix that and some other things. 

Merci d'avoir report :)

**Comment by epeeforteyt** [comment]
De rien l'ami :)
