### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by epeeforteyt** [FifouBE/EconomyInc#19]
J'ai une petite question, concernant les gold nuggets se qui ont un poids, on est obliger de passer par le four vanilla, serait-il possible de faire une compatibilité avec par exemple celui de Mekanism, car il n'a pas de poids il fois cuit.

Par la même occassion, sur le bloc Vending Machine, on est limité a 500$ d'échange, possible d'avoir une config que nous même on peut le config ? Merci d'avance

J'aurais peut-être d'autre question, possible via discord les questions: EpeeForte#4627

Labise

**Comment by Florent98** [comment]
Salut!

Pour l'instant la recette de la gold nugget pure passe par le furnace de minecraft et par les recettes json. Je ne sais absolument pas ce qu'il faut faire pour que ce soit compatible avec Mekanism.. Le block de vente est assez primaire pour l'instant mais ca devrait changer. Une fois que j'ai tout fix, je devrais commencer a rework le seller. Je compte ajouter une facon d'ajouter le montant custom de n'importe quelle valeur dans le futur!

Je t'ajoute sur discord en ami, n'hésite pas a me contacter en DM si tu as des questions plus poussées.

**Comment by Florent98** [comment]
Ah, tu as bloquer les demandes d'amis ^^ Voilà mon tag: [removed]

**Comment by epeeforteyt** [comment]
Ok thanks
