### ISSUE TITLE
Crash when loading on Dedicated Server

### ISSUE THREAD

**Issue by Nachtflame** [FifouBE/EconomyInc#2]
As per title & Crash report:
https://pastebin.com/t6txvDMw

in particular, Lines 42 & 43

> [22:36:56] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:block> dispatch for modid economyinc
java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

MC 1.14.4
forge-28.1.87
economyinc-1.6

**Comment by mike-t** [comment]
Same crash with: 
MC 1.14.4
forge-28.1.90
economyinc-1.6

thanks, this mod looks great!

**Comment by Florent98** [comment]
This issues has been fixed in the new version I just pushed to Curse. Thanks for the report!
