### ISSUE TITLE
Feature Request: Let op asign plots

### ISSUE THREAD

**Issue by puggan** [FifouBE/EconomyInc#22]
1. If the `/plotbuy`-command also took a playername argument
* then op:s could help players get there plot
* then commandblock could be used to assign plots

2. or add an `/plot assign`?

3. If the `/plot create`-command took an playername argument
* then op could set up plots that already have owners.

**Comment by Florent98** [comment]
That's great idea and will definitely implement that! 

Thanks for your comment.
