### ISSUE TITLE
[Bug] 1.15.2 Vending Block - Orders still processed with full inventory

### ISSUE THREAD

**Issue by mr-poyo** [FifouBE/EconomyInc#24]
Version: EconomyInc-1.6.8MC1.15.jar  
Forge: 31.1.41  

When purchasing an item from a Vending Block while your inventory is full, the order is still processed, but no item is given. i.e., the funds are subtracted, but the item never appears. Would be cool to have a check in place for this so that the order can't process. 

Steps to Reproduce:
1) Place a Vending Block with an item inside at a price (e.g., Bread for 500).
2) Fill your inventory with other objects (e.g., cobblestone).
3) Give yourself money: /balance add @p 500
4) Try to buy Bread from Vending Block.
5) Check balance /balance check @p && Check inventory for bread (should be missing).

**Comment by Florent98** [comment]
This is a known issue, it will be fix! Thanks for the report!
