### ISSUE TITLE
/plotbuy buy nameOfThePlot only works for Minecraft administrators (OPs) it does not work for players.

### ISSUE THREAD

**Issue by JustinJohnSullivan** [FifouBE/EconomyInc#26]
/plotbuy buy nameOfThePlot only works for Minecraft administrators (OPs) it does not work for players. If a player types "/plotbuy buy nameOfThePlot" the "buy" text is red and players get an "**Incorrect argument for command**" message when they try to run the command.

![plotbuy](https://user-images.githubusercontent.com/7001979/82946476-07862800-9f64-11ea-9dfa-5a11dde7b7fe.png)

**Comment by JustinJohnSullivan** [comment]
btw. We are using "**_EconomyInc-1.6.8MC1.14.jar_**" and I should also mention that we **LOVE** your mod. It is awesome! Would be even better if all players could purchase the plots. Thanks for the excellent work!

**Comment by JustinJohnSullivan** [comment]
_Note:_ Players have the upgraded credit card wireless technology to buy the plot and the plot was created by the admin _and_ the admin who created the plot can purchase the plot using the /plotbuy command, so the issue seems to only be with players. Thank you for any help you can provide.

**Comment by Florent98** [comment]
Hello! It was fixed in the version 1.6.9 of the mod for Minecraft 1.15. 

Unfortunately, the version for Minecraft 1.14 is not updated yet. So please be patient and be sure it's coming soon. 

Thanks for the report!

**Comment by Florent98** [comment]
Update was pushed!
