### ISSUE TITLE
[1.15.2] Crash with Ender Storage and Economic Inc

### ISSUE THREAD

**Issue by realTIMematrix** [FifouBE/EconomyInc#27]
Hi,

the game crashed and I don't know which mod produce the issue. I can only see that both mods together doesn't work.

Using:

- Forge: 31.2.0
- jei-1.15.2-6.0.0.4.jar
- EnderStorage-1.15.2-2.5.0.143-universal.jar
- CodeChickenLib-1.15.2-3.3.0.373-universal.jar
- economyinc-1.6.9.jar

Steps to reproduce:

1. Create new game in creative
2. Open Creative Tab and select transportation register (where the ender chest and tank are)
3. Game crashes

[lastest.log](https://pastebin.com/aeEW9xQv)

[crash.txt](https://pastebin.com/gRVukPDn)

I open the same ticket on the other mod page:
https://github.com/TheCBProject/EnderStorage/issues/127

Thank you for your help

**Comment by Florent98** [comment]
Hello!

I checked a bit can you try with this experimental see if the crash is still happening ?
[EconomyInc169Experimental.zip](https://github.com/FifouBE/EconomyInc/files/4713203/EconomyInc169Experimental.zip)

Thanks!

**Comment by covers1624** [comment]
https://github.com/FifouBE/EconomyInc/blob/master/src/main/java/fr/fifoube/main/capabilities/CapabilityMoney.java#L44 Entities can be constructed with null worlds for Rendering related things, move your profiler calls inside that If block and guard against a null world.

**Comment by Florent98** [comment]
I removed those lines, it was only for me during debugging.. I forgot to remove them from the mod once build. Just need confirmation that it was that the cause and I'll push the update.

Sorry about that!

**Comment by realTIMematrix** [comment]
> Hello!
> 
> I checked a bit can you try with this experimental see if the crash is still happening ?
> [EconomyInc169Experimental.zip](https://github.com/FifouBE/EconomyInc/files/4713203/EconomyInc169Experimental.zip)
> 
> Thanks!

Experimental Version works. If you release this version this would be nice. Then we can close this issue

**Comment by Florent98** [comment]
I was just waiting for your confirmation. Perfect! I'll push the update as soon as I can!
