### ISSUE TITLE
[1.15.2] Request minecraft stat for using Gold Changer

### ISSUE THREAD

**Issue by mr-poyo** [FifouBE/EconomyInc#29]
Hello,

I am trying to do some command-block/scoreboard magic to limit how many times a player can use the gold changer per day, but I cannot find a good minecraft stat to use. Would it be possible to add a minecraft stat for this particular case?

![economyInc](https://user-images.githubusercontent.com/11811815/84212877-fe679000-aaf9-11ea-87e6-940530a7661c.PNG)

I was thinking it would be cool to fire when the person removes their credit card from the Gold Changer like below:
![economyInc2](https://user-images.githubusercontent.com/11811815/84212968-6027fa00-aafa-11ea-81fd-d8b711818f62.PNG)

My idea is to use command blocks to detect when X gold nuggets are used then i'll auto-teleport the player away from the changer until the next day. 

If this is too complicated, no worries, I can always use a clock timer and give them 5 minutes inside the room, but I was hoping to use a stat to be more precise. Thanks for reading!

**Comment by Florent98** [comment]
I managed to add a statistics but I don't know if it will be useful. It increase the number by one everytime gold is changed in the machine. But I don't know if scoreboard objectives is the same as minecraft statistics tab.. I'll try experimenting that.
