### ISSUE TITLE
[1.15.2] Server crash when player joins server

### ISSUE THREAD

**Issue by mr-poyo** [FifouBE/EconomyInc#31]
Version: 1.6.9
Forge: 31.2.20

**Update:** More than likely its the rftools builder 'quarry. '  i suspect it's not related to economy inc at all. When he removed the builder, the server stops hanging. 

Hello again, 
On my server, whenever a certain player joins, the server is stalling then eventually crashes (100% of the time). The log looks like it may have something to do with economy inc and RFtools builder. The player says he does have RFtools builder at his base.

Crash report: https://pastebin.com/1g7WbCdE

Any insight if this is something we can fix on our end?

**Comment by Florent98** [comment]
Hello have you found the cause ?

**Comment by mr-poyo** [comment]
Hello,

I would like to reopen this issue. With a new crash log that is not referencing RFTools:

crashlog: https://pastebin.com/57C9d4XB

This time, I am destroying a block in somebody else's territory. I should mention that we have Thut's essentials which has a ''claim chunk'' feature with permissions and such. I am an OP in creative mode trying to punch a block and this crash happens. Seems like it might be similar to the RFTools Quarry as that also breaks blocks.

**Update:** I restarted the server, and tried breaking a block outside a territory, still crashed. This is bizarre because we had no issues previously. I did add some plots and then later removed them. could it have bugged something? right now the server should have no plots. **Another thought:** the guy I banned purchased a plot. I have since /plot removed it. Possibly a coincidence?

**Solution[?]:**
I went into my server files, and deleted all the plot data here:
![image](https://user-images.githubusercontent.com/11811815/85537858-4edd0280-b64f-11ea-9f1e-05af0330ec70.png)
We are now able to break blocks again. I will ask the player with the Quarry if it's working now when he logs in. Still might be nice to find the cause though, as I am afraid to use /plots at the moment

**Comment by Florent98** [comment]
It’s really, I had no problem testing the mod alone.  The server is running behind as you can see in the crash log but it’s really weird it might be related with the claim chunk mod you have , I’ll try it on my own see why it crashes.

**Comment by mr-poyo** [comment]
Deleted the .dat files fixed the issue. Confirmed with player using a Quarry. Thanks!

**Comment by Florent98** [comment]
Be careful that deleting those files will remove every plot on the server. I'll try to investigate myself to see if the bug is happening because it's an object mining and not a player. Thanks.
