### ISSUE TITLE
Command to exchanged !!

### ISSUE THREAD

**Issue by zeven001** [FifouBE/EconomyInc#32]
Hi i need help with mod how to do use exchange to gold?

**Comment by Florent98** [comment]
Please rewrite your issue in english. I do manage to understand spanish, but I would like to be 
1. sure of what you are saying
2. keep this github issue only english (universal language)

Thank you!

**Comment by zeven001** [comment]
sorry this my question What is the command for the change of gold?

**Comment by Florent98** [comment]
The change of gold is not accessible by command, it's in the config files server side, in your world files in server config and in the file economyinc-server.toml that you can open with any text editor, change the line "multiplierGoldNuggetWeight = 2" , you can change the number to any number from 1 to 9999.

**Comment by zeven001** [comment]
THANKS ALOT!!!
