### ISSUE TITLE
What are all the commands for admins?

### ISSUE THREAD

**Issue by Crmble** [FifouBE/EconomyInc#33]

**Comment by Florent98** [comment]
Hello there are many commands.

/balance add/remove/check Player amount (amount is only needed with add and remove)

/plot create x1 y1 z1 x2 y2 z2 UniqueName Price (create a plot with a certain price)
/plot remove NameOfThePlot (Remove the plot with that name)
/plot assign Player NameOfThePlot (Assign a plot to a player without making them buying)
/plot teleport NameOfThePlot Player (Teleport a player [can be used with @a @e etc] to a certain plot)

/plotbuy buy NameOfThePlot (Allow a player to buy a plot not already bought)

**Comment by Crmble** [comment]
What about for the gold converter

**Comment by Florent98** [comment]
There are no commands for gold convertor. If you need to change the multiplier, it's in the config of the server.

Are you looking to do something in particular ?

**Comment by Crmble** [comment]
How do I enable it?

**Comment by Florent98** [comment]
The config ?

**Comment by Crmble** [comment]
Im running a server from my own pc. How do I enable it from there?

**Comment by Crmble** [comment]
![Capture](https://user-images.githubusercontent.com/68199405/87261090-6eab5d80-c47a-11ea-9156-6b053cce8e79.PNG)

**Comment by Florent98** [comment]
You normally have a folder, in your server folder, named server-config, it's in there. the .toml can be opened with any text editor.

**Comment by Crmble** [comment]
I don't have the one for Economyinc in there
not sure why its not there. Mind sending me a copy of what's in there?

**Comment by Florent98** [comment]
It's in world > serverconfig > economyinc-server.toml

**Comment by Florent98** [comment]
If you still don't find it, I can send you a copy but I'm 99% sure it's there

**Comment by Crmble** [comment]
Ah i found it, but what do i need to do to enable the gold converter?

**Comment by Florent98** [comment]
It's enabled by default. You need to placed an updated linked credit card in the bottom slot and the top slot should be the the pure gold nugget (the one from the mod) after some time it will process.

**Comment by Crmble** [comment]
Oh cool, one more question, how to I upgrade the card?

**Comment by Florent98** [comment]
You just need to have a creditcard (created of course, so by shift right clicking the card), then with the microchip, you right click it (with the credit card still in your inventory) and it will upgrade the credit card.

**Comment by Crmble** [comment]
That doesnt work for some reason

**Comment by Florent98** [comment]
Do you have any message in the chat ?

**Comment by Crmble** [comment]
Nope

**Comment by Crmble** [comment]
It just dissapears

**Comment by Florent98** [comment]
Then the card is updated, when you hover the credit card does it says Owner : YourName Linked : Yes ?

**Comment by Crmble** [comment]
No, it just says Upgraded:no

**Comment by Florent98** [comment]
Do you have the credit card in your hotbar ?

**Comment by Crmble** [comment]
Yup

**Comment by Florent98** [comment]
It's really weird. Could you send a video ? Because just like that it's hard to see what is wrong..

**Comment by Crmble** [comment]
sure

**Comment by Crmble** [comment]
[2020-07-12 20-16-05.zip](https://github.com/FifouBE/EconomyInc/files/4910081/2020-07-12.20-16-05.zip)
Sorry about the weird folder, github doesnt support mp4

**Comment by Florent98** [comment]
Hmmm, that's very strange are you with the latest version in 1.15.2 ? Did you try remove the credit card, get a new one and try upgrading it ?

**Comment by Crmble** [comment]
Ive done all of that, and Yes im in 1.15.2

**Comment by Florent98** [comment]
Nothing in the console ?

**Comment by Crmble** [comment]
![image](https://user-images.githubusercontent.com/68199405/87261821-4bce7880-c47d-11ea-9652-53ac9f166343.png)

**Comment by Florent98** [comment]
Oh, ok I got it so you have version 1.6.9.3 of the mod ? Just to be sure, sorry for all those questions

**Comment by Crmble** [comment]
I think so. Is that the problem?

**Comment by Florent98** [comment]
No no, it means I have pushed a wrong update, I need to fix it.

**Comment by Crmble** [comment]
Oh lol

**Comment by Florent98** [comment]
I will push it tomorrow, since it's late for me here.

**Comment by Crmble** [comment]
Alright but also, sometimes peoples funds will reset to zero.

**Comment by Florent98** [comment]
Are you sure you are using the latest version OF the mod ? Because that's a bug that was resolved months ago, please refered to that page https://www.curseforge.com/minecraft/mc-mods/economy-inc

**Comment by Florent98** [comment]
Hello did you find the version you need or are you still waiting for help ?

**Comment by Florent98** [comment]
I consider this issues closed. Please if you have any problems, open a new issue. Thank you!
