### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by cam7minus1** [FifouBE/EconomyInc#35]
I am not sure where I can get a list of the commands, but only operators can use commands. I tried looking for permissions but it keeps coming up dry. Is the mod broken, or are we doing something wrong?

**Comment by Florent98** [comment]
You have a list of commands on the official thread : https://www.curseforge.com/minecraft/mc-mods/economy-inc

it's at the bottom of the mod explanation !

**Comment by cam7minus1** [comment]
Ah I figured it out, another mod was fighting with eco inc. Thanks!
