### ISSUE TITLE
Deposit Bug with more than 1 Stack of Bills.

### ISSUE THREAD

**Issue by Patrick1417** [FifouBE/EconomyInc#37]
I found a bug while adding cash to my bank account.

If you have serveral Stacks of the same bill, it will substract 1 of each, but only count 1.

 

For example, i have 3 Stacks of 1 Dollar bills in my inventory, i open my credit card to deposit the money into my bank account, press the +1 Button, it will substract 1 of each of the stacks, but will only count for 1 in my bank account. 

 

Could you please fix this problem? 

 

Thank you.

**Comment by Florent98** [comment]
Hello,

thanks for the report, indeed a check was not done server side. It's fixed in version 1.7!
