### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Patrick1417** [FifouBE/EconomyInc#38]
Would it be possible to make "Sell" blocks? Like the other buying blocks, just for selling (maybe infinity selling like at the buying blocks)
An Admin determs what item can be sold here and for what price. 

It also would be nice if you can adjust the amount of money you need to pay at the buying blocks for more than 500$, maybe 3x 500 or even more.

Thanks

**Comment by Florent98** [comment]
Hello, I think what you are asking is coming a future version of the mod. It's in preparation stay tuned !
