### ISSUE TITLE
Gold changer crashes server

### ISSUE THREAD

**Issue by 64thParaDux** [FifouBE/EconomyInc#42]
had to disable and not use because of it. using with TNP Limitless 3

**Comment by Florent98** [comment]
Hello are you able to provide the minecraft version you are using, mod version and the crash report so I can check that ?

Also what's the step to reproduces for the crash to happen?

 Thank you !

**Comment by Florent98** [comment]
Hello @64thParaDux,

I just tried a server TNP Limitless 3 with Economy Inc added, and I have no crash happening with the server and this modpack, are you able to send me a crash report ? Have you added other mod to the default modpack also ? Thanks

PS: Without any written logs I can't do anything to solve the problem.. If I have no response in 7 days I'll have to close that case.. :/

Thank you!

**Comment by 64thParaDux** [comment]
Hello I am so sorry I do not currently have the crash log anymore if it crashes the server again we will send the crash log with a new issue for sure.
