### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by DogeMomentt** [FifouBE/EconomyInc#44]
When you apply the wireless ability to the card, if you have something in your offhand the wireless ability thing will get replaced by whatever is in your offhand

**Comment by Florent98** [comment]
Hey, thanks for the report, it is fixed in the future version of the mod! :)

**Comment by pizzaboymax** [comment]
Hello wehn will you fix this glitch, we want to work whith this mod. But whit this glitch you could coppy every Item you want, also Diamonds and other stuff. could you please fix this

**Comment by Florent98** [comment]
Hello it is fixed in future patch that is coming but there was major changes between 1.16 and 1.17 so it's coming don't worry :)

**Comment by Florent98** [comment]
Fixed.
