### ISSUE TITLE
Vending machine only sells one item

### ISSUE THREAD

**Issue by jakecroftford** [FifouBE/EconomyInc#45]
Not sure if this is a bug but if I put more than one item in a vending machine while setting it up such as 16 bread it displays as if its going to give 16 bread for the set price but instead just gives one for the price. Also is there no way to make more varied prices in vending machines like if you choose $1 twice it would set the price at $2

**Comment by Florent98** [comment]
Hello, 
this is not a bug. Seller only sells one item at a time, the cost you see is the cost for one item.

However in the next version you'll get a new way of selling, with the price you desire :)
Stay tuned :)
