### ISSUE TITLE
Seller Cooldown Resets When Server Is Restarted

### ISSUE THREAD

**Issue by TornadoGamer10** [FifouBE/EconomyInc#47]
If I restart my server, it sets the cooldownSeller to 20. I'm not sure if this is a feature or a bug. I always keep it at 0 (Not sure if that makes a difference) All of the other settings in the config file stay the same except for the cooldownSeller option.

**Comment by Florent98** [comment]
Hello, this is normal. Seller cooldown range is between 20 - 500. It prevents a lot of problem, especially on the server side that can sometimes be slower and duplicate some of the items sold. 

``#Cooldown applied for the seller, prevent fast buy.
#Range: 20 ~ 500
cooldownSeller = 20``
	
Here is where it said
