### ISSUE TITLE
Smelting gold ingots crashes server

### ISSUE THREAD

**Issue by dwightdurmon** [FifouBE/EconomyInc#48]
Hello...

Here is a link to the crashlog: (https://pastebin.com/6tqwX1cj ) (didn't want to post here because it is so long and ugly).

```
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-29-generic
	Java Version: 11.0.10, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 675325672 bytes (644 MB) / 2352701440 bytes (2243 MB) up to 4054515712 bytes (3866 MB)
	CPUs: 1
	JVM Flags: 2 total; -Xms128M -Xmx4000M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.30.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.30
```

======
Let me know if you need any additional information and I'll be happy to pull it from the server.

Thanks!

**Comment by Florent98** [comment]
Hello!

Can you tell me the configuration you have while the crashes happen, like what's in your inventory, are there other players ?
Also it seems to happen when you place the nugget inside the gold changer, can you confirm ?

Thanks! A picture of your inventory before the crash would be perfect.

**Comment by dwightdurmon** [comment]
Hello,

For the inventory, it's a random assortment of items, varying by player.  Our server has 4 players on it and the crash has happened to each of us independently.  The crash occurs when we put the gold bar into a Furnace to make a Pure Gold Nugget.

I have uninstalled the mod from the main server.  I'll spin up a backup copy of the server in the next day or so with the mod installed and see if I can get it to crash again and get a picture of my inventory.

Cheers!

**Comment by Florent98** [comment]
Hello,

weird I can't seem to reproduce the bug, I suspect a mod conflict, do you have other mods on the server ? From the crash report it seems to be the block changer that crashes but I can't seem to understand why.. At least without reproducing it I can't seem to understand which parts makes the grame crash.

If it crashes directly when you place the gold bar into the furnace then it's a conflict, because it doesn't happen on my end.
