### ISSUE TITLE
Recommendation for the mod.

### ISSUE THREAD

**Issue by MonarchGamingFB** [FifouBE/EconomyInc#49]
Hey, so I have been using the mod for some time now. It's for a server that I have created. Now I have jobs on my server and want a way to **pay users periodically**. And a way to **remove money** from an account periodically like taxes/bills etc... Is this something that you could do as it would **mean a lot** to me and would improve a lot for servers like my own. Thanks!

**Comment by Florent98** [comment]
Archievable with commands blocks or servers commands plugin/mod.
