### ISSUE TITLE
crash server 

### ISSUE THREAD

**Issue by tiphilou17** [FifouBE/EconomyInc#5]
forge 107 minecraft  1.14.4

one crash and after its ok... with gold changer, vending machine (not click possible) muste replace to use.

https://gist.github.com/tiphilou17/e763fdba165d7f50778643d26e7489e6

**Comment by Florent98** [comment]
Hello, 

Can you explain exactly the step to reproduce the bug ? Thanks! I'll look into it as soon as I recover my computer

**Comment by tiphilou17** [comment]
1- i have gold changer in my inventory
2- i take in my hand item and go to place
3- crash server

reboot

1- i have vending machine in my inventory
2- i take in my hand item and go to place
3- crash server
4-reboot
5- no click on this vending its possible
6- destroying vending 1 and place vending 2 (no crash), its ok validate price item...but i am the only player can open interface, other guy can't click on my vending.

**Comment by Florent98** [comment]
Hello,

Thanks for those steps, I'll try to reproduce the bug, even tho it's really weird that it's happening. The bug with the vending machine was fixed and released on Curse. Is this the full crash? Can you post the log ?

**Comment by tiphilou17** [comment]
its ok with EconomyInc 1.6.3 - MC1.14, vending machine work and gold changer no crash but no dolllars (not implemented i think), good work

**Comment by Florent98** [comment]
No dollars, where ?

**Comment by tiphilou17** [comment]
in gold changer, i place card upgraded and pure nugget gold but no result, no click on any money changing.

**Comment by Florent98** [comment]
Does your pure gold nugget has a weight ? It gives you a weight by smelting gold ingot into a furnace. It's a feature that is still raw tho, so I'll work on it ;)

**Comment by tiphilou17** [comment]
in give admin no work no weight, in survival process furnace and inventory its ok wieht appear, perfect work.
