### ISSUE TITLE
Pure Gold Nuggets Not Having Weight On Survival Mode

### ISSUE THREAD

**Issue by PlayerUmut** [FifouBE/EconomyInc#53]
When I Was Smelting A Gold For Money, It Came As A Pure Gold Nugget Without Any Weight Information. When I Tried To Convert It To $, It Didn't
Server : Aternos
Client : Forge 1.17.1
Mods : Economy Inc.
SecurityCraft
Just Enough Items

**Comment by Florent98** [comment]
Fixed, place pure gold nugget into changer now to weight it and add to card.
