### ISSUE TITLE
vending machine 

### ISSUE THREAD

**Issue by tiphilou17** [FifouBE/EconomyInc#6]
FORGE 107 Minecraft 1.14.4
i place a vending machine, 64 furnaces to 200$, validate, and i click i have the vending interface but my friend no click possible, and with friend's machine i can't click on his VM.

**Comment by Florent98** [comment]
Hello, 
Thanks! I'll look into it as soon as I recover my computer

**Comment by Florent98** [comment]
Hello, I have resolved the problem, it was a mistake from me. It will be pushed as soon as other bugs are fixed.
