### ISSUE TITLE
Is 1.16.5 abandoned?

### ISSUE THREAD

**Issue by Neonn2020** [FifouBE/EconomyInc#61]
There are bugs..
You can’t bet more than $500 in a vending machine, but at the same time, you can withdraw as much as you like from the card...

**Comment by Florent98** [comment]
Hello, it's normally up to date, but I don't support it anymore since it's a lot of work to have 3 version running. Sorry.

What are the bugs, I don't understand the bet more than 500$ in the vending machine ?
Also you can withdraw what you have on your card nothing more.

**Comment by Shadowdu54** [comment]
@Florent98 bonjour ça serait possible de le mettre en version 1.19.2 ???
