### ISSUE TITLE
Funds=0.0 after death

### ISSUE THREAD

**Issue by Locap4** [FifouBE/EconomyInc#8]
I'm playing with the beta version for 1.15.2 on a Forge Server.

When i die I have no more money on my credit card and it behaves like it hasn't been upgraded with the micro chip.

However when I disconnect for awhile (5-10min) and reconnect everything comes back to normal, my funds is the same as before i died and my credit card is upgraded.

**Comment by EnterFor** [comment]
Hope the author can fix it

**Comment by Florent98** [comment]
Got it fixed! Thanks for the report :)
